---
title: "Report"
output: github_document
---




```{r}
library(dplyr)

arrange(summarise(group_by(tables, name), 
                  total = sum(shot_type == "2PT Field Goal"), made = sum(shot_made_flag == "shot_yes" & shot_type == "2PT Field Goal"), percentage = made/total), desc(percentage))
arrange(summarise(group_by(tables, name), 
                  total = sum(shot_type == "3PT Field Goal"), made = sum(shot_made_flag == "shot_yes" & shot_type == "3PT Field Goal"), percentage = made/total), desc(percentage))
arrange(summarise(group_by(tables, name), 
                  total = sum(shot_type == "2PT Field Goal" | shot_type == "3PT Field Goal"), made = sum(shot_made_flag == "shot_yes"), percentage = made/total), desc(percentage))



```

Report: 

Introduction: 
They're currently the best sports team. They rose to fame in the past decade, and have been dominating their respective sports brackets ever since. They have big, big names on their team, and the star players insist that their success is attributed to the entire team, and not only of one player. And I'm not talking about the Patriots. I'm talking about the Golden State Warrior. But how much are they really better by? Is Curry really that much better than the others on his team? What are their tendencies? Let's take a closer, actual look at the intricacies of the shot taking mechanisms of the team. We'll look at how Iggy likes to do lay ups while Curry sinks the threes, while Draymond is a god in the paint and how Durant is kind of good at nothing. This is an in depth article about the Golden State Warriors and all the data you could dream of about their shooting. 
Motivation: The motivation for writing this article is that it's a requirement at the end of the Stats 133 Workout1. Why it needs to be a thousand words long, I don't know, but it does. So, get ready for some verbose language. Whatever the opposite of "Eschew obfuscation" is. The main focus of this article is going to be analyzing the shooting patterns of the 5 top stars on the Golden State Warriors. We have Andre Iguodala, Draymond Green, Kevin Durant, Klay Thompson, and of course, the goat Stephen Curry himself. But first, a little background. 

Background: All the data found here has been provided by a third party. The charts, images, and tables made have all been created by yours truly through the great functions and tools that R has to provide. Now, let's get into some more numbers. 
Analysis of Data: Lets take a look at the gsw-shot-chart found in the images folder. It's clear to see that the five different players have drastically different shooting styles. Some of them choose to shoot in a more close range method, while others tend to sit a little further back. You can notice a clear "bush" of shots around a rim of a radius of the hoop. This is because in basketball, you're awarded 3 points for a shot that it outside a certain perimeter. It clearly makes more sense to step back and go for 3 points, in stead of going slightly closer and settling for two. Let's look at the data a little more closely. The average shot distance for the entire team is a whopping 15.58 feet from the hoop. This is surprisingly high considering the number of lay ups that are performed, but upon further evaluation it's understandable considering the fact that each of these lay ups are off set with a shot from the 3 point range. The 1st quartile is 2.25 feet, which accounts for all the layups made. Now, let's see how each of the players differ from the team average. We can see different styles given different positions; point guards are more likely to take three pointers, while centers probably won't shoot a three that often. 
Curry: As expected, Curry's average shot distance is further than average. He comes in at 17.99 feet on average from the hoop, which can probably be attributed to the fact that he takes the most three pointer shots in the league. 
Green: Green, on the other hand, can be observed to be shooting on average 12.17 feet from the hoop, which is significantly closer than Curry. It makes sense though! He's a much taller person, so he should use his height to his advantage at a spot much closer to the hoop. It's easier for him to make close shots than it is for him to make far shots. 
I'd go through the rest of the players, but honestly we get the idea; shot distance is one of the many ways that the players differ from each other. Let's try to find some more. 
Probably the most striking visual there is the lack of shots that Andre Iguodala puts out. Why so few? Because his position doesn't demand it. However, all the players have a large amount of shots within 5 feet of the rim. What about the paint, you say? Let's take a look. Draymond Green seems to be lacking in shots from the paint as well. Durant however, excels at it. He has the highest paint shots, as well as highest paint make percentage out of the entire 5 starters. Klay Thompson seems to like the paint too., coming in at second. Stephen Curry however seems to spend most of his time on either the outskirts or running up for layup. With his size and stature, the paint isn't the most optimal place to take shots for him. A quick note: it seems like the things that I'm saying are opinions, but they're really not. The data speaks for itself. Out of literally thousands of shots, it's clear to see that there are preferences for each player. 
Conclusion: The data that was provided for us was used to build a solid number of graphics, as well as tables that summarized the players tendencies. There were a few things that we could have delved into, but given the size of this article already, I feel like it's not the time or place. A few cool things we could have looked at are the times at which players take the most shots, the distance and how it changes as the time of the game wears on. And the number of shots as the period comes close to an end. The data provided should be sufficient to take a look at all of these, and how they differ per player. TLDR: (because honestly it's too long, I'd be surprised if you read it all). The players of the Golden State Warriors differ widely in their shot taking techniques and preferences. We used R code and data to analyze and provide appealing visuals to be able to see this in a more clear fashion. TLDRR: Stephen Curry and the Warriors are a great team. 
 

